# Site settings
title: Ordina ORAJ Tech Blog
email: info@ordina.be
description: > # this means to ignore newlines until "baseurl:"
  Ordina ORAJ Tech blog
metadata:
  keywords: Ordina,ORAJ,Blog,Java,Javascript,DevOps
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ordina-oraj.github.io" # the base hostname & protocol for your site
twitter_username: lifeatordinabe
github_username:  ordina-oraj
facebook: lifeatordinabe
gems: [jekyll-paginate]
# Build settings
markdown: kramdown

# Pagination
paginate: 10